# Generated by Django 5.1.3 on 2024-11-28 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Black', 'Black'), ('Green', 'Green'), ('Masala', 'Masala'), ('Herbal', 'Herbal'), ('Oolong', 'Oolong'), ('White', 'White'), ('Yellow', 'Yellow'), ('Pu-erh', 'Pu-erh'), ('Matcha', 'Matcha'), ('Chai', 'Chai'), ('Chamomile', 'Chamomile'), ('Peppermint', 'Peppermint'), ('Ginger', 'Ginger'), ('Lemon', 'Lemon'), ('Hibiscus', 'Hibiscus'), ('Rooibos', 'Rooibos'), ('Yerba Mate', 'Yerba Mate'), ('Lavender', 'Lavender'), ('Jasmine', 'Jasmine'), ('Earl Grey', 'Earl Grey'), ('English Breakfast', 'English Breakfast'), ('Assam', 'Assam'), ('Darjeeling', 'Darjeeling'), ('Nilgiri', 'Nilgiri'), ('Ceylon', 'Ceylon'), ('Keemun', 'Keemun'), ('Lapsang Souchong', 'Lapsang Souchong'), ('Sencha', 'Sencha'), ('Genmaicha', 'Genmaicha'), ('Gunpowder', 'Gunpowder'), ('Longjing', 'Longjing'), ('Matcha', 'Matcha'), ('Chun Mee', 'Chun Mee'), ('Gyokuro', 'Gyokuro'), ('Kukicha', 'Kukicha'), ('Pi Lo Chun', 'Pi Lo Chun'), ('Tencha', 'Tencha'), ('Yabukita', 'Yabukita'), ('Yame', 'Yame'), ('Yun Wu', 'Yun Wu'), ('Chamomile', 'Chamomile'), ('Peppermint', 'Peppermint'), ('Ginger', 'Ginger'), ('Lemon', 'Lemon'), ('Hibiscus', 'Hibiscus'), ('Rooibos', 'Rooibos'), ('Yerba Mate', 'Yerba Mate'), ('Lavender', 'Lavender'), ('Jasmine', 'Jasmine'), ('Earl Grey', 'Earl Grey')], max_length=100)),
            ],
        ),
    ]
